ref: .test/reference/chm13_v1.1_plus38Y_masked.fasta
manifest: .test/manifest.tsv
metadata: .test/hprc_year1_sample_metadata.txt 
step_size: 100000
window_size: 200000
min_syntenic_size: 1000000
annotation_files:
  SD: .test/annotation/chm13_v1.1_plus38Y.SDs.bed.gz
  Sat: .test/annotation/chm13_v1.1_plus38Y.cen.bed.gz
  Unique: .test/annotation/unique.bed.gz
  TRF: .test/annotation/TRF.fake.bed.gz
