ref: .test/reference/chm13_v1.1_plus38Y_masked.fasta
manifest: .test/manifest.tsv
metadata: config/hprc_year1_sample_metadata.txt
step_size: 100000
window_size: 100000
min_syntenic_size: 1000000
annotation_files:
  sd: .test/annotation/chm13_v1.1_plus38Y.SDs.bed.gz
  cen: .test/annotation/chm13_v1.1_plus38Y.cen.bed.gz
